# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logchatmessages',
            options={'verbose_name': 'LogChatMessage', 'verbose_name_plural': 'LogChatMessages'},
        ),
    ]
