# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 09:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170122_0943'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LogChatMessages',
            new_name='LogChatMessage',
        ),
    ]
