# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 10:53
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170122_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='logchatmessage',
            name='original_msg',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
