# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20170126_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_deal_sent_id',
            field=models.IntegerField(default=0, verbose_name='Last Deal Sent'),
        ),
    ]
