# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_userprofile_last_deal_sent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='link',
            field=models.URLField(default='', verbose_name='Deal URL'),
        ),
    ]
