# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_deal_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='link',
            field=models.URLField(default=str, verbose_name='Deal URL'),
        ),
    ]
