# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 02:10
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20170126_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='interest',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), default=list, size=None, verbose_name='Interests'),
        ),
    ]
