# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20170204_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_deal_checked_id',
            field=models.IntegerField(default=0, verbose_name='Last Deal Checked'),
        ),
    ]
