# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 05:15
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_userprofile_last_deal_checked_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='raw',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
