# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_logchatmessage_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='logchatmessage',
            name='fromwhom',
            field=models.CharField(default=str, max_length=150, verbose_name='Who sent this'),
        ),
    ]
