# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_logchatmessage_fromwhom'),
    ]

    operations = [
        migrations.AddField(
            model_name='logchatmessage',
            name='direction',
            field=models.CharField(choices=[('DI', 'Incoming'), ('DO', 'Outgoing')], default='DI', max_length=2, verbose_name='Message Direction'),
        ),
    ]
