# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_logchatmessage_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logchatmessage',
            name='kind',
            field=models.CharField(choices=[('MU', 'Unknown'), ('MCAI', 'Add Interest'), ('MCRI', 'Remove Interest'), ('MCL', 'Latest Deals'), ('MCLI', 'List Interests'), ('MCS', 'Start'), ('MCH', 'Help'), ('MR', 'Response')], default='MU', max_length=5, verbose_name='Kind'),
        ),
    ]
