# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20170212_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logchatmessage',
            name='direction',
            field=models.CharField(choices=[('I', 'Incoming'), ('O', 'Outgoing')], default='I', max_length=1, verbose_name='Message Direction'),
        ),
    ]
