# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-25 07:18
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_deal_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='Store Key')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='Data Store')),
            ],
            options={
                'verbose_name': 'Data Store',
                'verbose_name_plural': 'Data Stores',
            },
        ),
    ]
