# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-16 11:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_datastore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logchatmessage',
            name='kind',
            field=models.CharField(choices=[('MU', 'Unknown'), ('MCAI', 'Add Interest'), ('MCRI', 'Remove Interest'), ('MCL', 'Latest Deals'), ('MCLI', 'List Interests'), ('MCS', 'Start'), ('MCH', 'Help'), ('MR', 'Response'), ('MCRI', 'Reset'), ('MCON', 'Contact')], default='MU', max_length=5, verbose_name='Kind'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='duser',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
